### ISSUE TITLE
passwordguesser failing

### ISSUE THREAD

**Issue by sheerazali19** [quentinhardy/odat#34]
/opt/odat   master ●  ./odat.py passwordguesser -s 10.10.10.82 -d XE --accounts-file accounts/oracle_default_userpass.txt 

[1] (10.10.10.82:1521): Searching valid accounts on the 10.10.10.82 server, port 1521
Traceback (most recent call last):
  File "./odat.py", line 557, in <module>
    main()
  File "./odat.py", line 552, in main
    arguments.func(args)
  File "/opt/odat/PasswordGuesser.py", line 185, in runPasswordGuesserModule
    passwordGuesser.searchValideAccounts()
  File "/opt/odat/PasswordGuesser.py", line 98, in searchValideAccounts
    pbar,nb = self.getStandardBarStarted(len(self.accounts)), 0
  File "/opt/odat/OracleDatabase.py", line 261, in getStandardBarStarted
    return ProgressBar(widgets=['', Percentage(), ' ', Bar(),' ', ETA(), ' ',''], maxval=maxvalue).start()
  File "/opt/odat/progressbar.py", line 213, in __init__
    assert (maxval > 0),'maxval <= 0' 
AssertionError: maxval <= 0

**Comment by quentinhardy** [comment]
`oracle_default_userpass.txt` is not a default file of ODAT. I think your password file is empty. Put credentials in this file and it will work.
