### ISSUE TITLE
dbmsscheduler errors on python3.8.5

### ISSUE THREAD

**Issue by dreamer2q** [quentinhardy/odat#54]
with python 3.8.5

got following errors when use module dbmsscheduler

```python
Traceback (most recent call last):
  File "./odat.py", line 586, in <module>
    main()
  File "./odat.py", line 581, in main
    arguments.func(args)
  File "/root/odat/DbmsScheduler.py", line 178, in runDbmsSchedulerModule
    dbmsScheduler.giveReverseShell(localip=args['reverse-shell'][0],localport=args['reverse-shell'][1])
  File "/root/odat/DbmsScheduler.py", line 128, in giveReverseShell
    CMD = '''/usr/bin/python -c exec('{0}'.decode('hex'))'''.format(PYTHON_CODE.encode('hex'))
LookupError: 'hex' is not a text encoding; use codecs.encode() to handle arbitrary codecs
```

**Comment by quentinhardy** [comment]
Hello,
Can you test the last version please? It should fix this bug.
