### ISSUE TITLE
not working module

### ISSUE THREAD

**Issue by totomano200** [quentinhardy/odat#57]
Traceback (most recent call last):
  File "./odat.py", line 5, in <module>
    from libnmap.parser import NmapParser
ImportError: No module named libnmap.parser

sudo pip3 uninstall NmapParser                                                                                                                              1 ⨯

Found existing installation: nmapparser 0.2.5
Uninstalling nmapparser-0.2.5:
  Would remove:
    /usr/local/lib/python3.9/dist-packages/nmapparser-0.2.5.dist-info/*
    /usr/local/lib/python3.9/dist-packages/nmapparser/*
Proceed (y/n)? y
  Successfully uninstalled nmapparser-0.2.5

sudo pip3 install NmapParser                                                                                                                                1 ⨯

Collecting NmapParser
  Using cached nmapparser-0.2.5-py3-none-any.whl
Installing collected packages: NmapParser
Successfully installed NmapParser-0.2.5

still get same error

./odat.py -h                  
Traceback (most recent call last):
  File "./odat.py", line 5, in <module>
    from libnmap.parser import NmapParser
ImportError: No module named libnmap.parser

**Comment by totomano200** [comment]
working with only adding 
python3 odat.py -h
